### ISSUE TITLE
Convert array to `[Flags]` enum

### ISSUE THREAD

**Issue by xperiandri** [Tarmil/FSharp.SystemTextJson#115]
Is it supported to convert an array of strings to a `[Flags]` enum?
``` JSON
"allowedCustomerOperations": [
      "Delete",
      "Update",
      "Read"
  ],
```
``` F#
[Flags]
type AllowedCustomerOperations =
| Read = 0
| Update = 1
| Delete = 2

**Comment by Tarmil** [comment]
Since flag enums are a general .NET feature and not specifically F# types, I don't want to handle them in FSharp.SystemTextJson. But I think this would be a great suggestion to make in https://github.com/dotnet/runtime for inclusion in System.Text.Json itself, as optional behavior for its built-in `JsonStringEnumConverter`.
