### ISSUE TITLE
Treat single-case union as the value

### ISSUE THREAD

**Issue by drhumlen** [Tarmil/FSharp.SystemTextJson#26]
```f#
type PersonId = PersonId of int
let person = {| Name = "Tarmil"; PersonId = PersonId 123 |}
```

I would expect person to be formatted as

`{name: "Tarmil", personId: 123}` in the example above, not as:
`{name: "Tarmil", personId: {Item: 123}}` which is the closest thing I've found using options:`JsonUnionEncoding.BareFieldlessTags ||| JsonUnionEncoding.Untagged`.

Is it possible to add a super simple formatter specifically for Single-Case DUs? They're a really common pattern in F#, and we're using them to wrap basically all our primitives to add semantic meaning to them.

E.g. Map<PersonId, ProfileInfo> makes a lot more sense than  Map<string, ProfileInfo> in which case you have to remember that the string refers to a person id. Single-Case DUs makes everything very easy to comprehend 😄 

Maybe there already is support for it?

**Comment by drhumlen** [comment]
@bartelink : I tried out FSharp.UMX now. It looks very nice! I'm tempted to replace all our usage on single-cased DUs with this.

Is there any reason to be hesitant about doing this? Do you advice for or against it?

**Comment by bartelink** [comment]
Yes, Eirik and Alfonso have done us a great service; I've used it in quite a few contexts and find it hard to fault in general. Some things to point out:
- both sides of a contract can interop without sharing an assembly
- normal reflection won't be able to separate the id type from its underlying type - great for serialization and/or e.g. strong typing all sorts of other things like LINQ etc
- if the underlying type is a `Guid` but your canonical rendering demands formatting it with `Guid.ToString("N")`, you're in peril and will probably forget to register your custom Guid Converter
- doesnt play well with unquote (but that normally forces you to Do The Right Thing)
- you can make a mess by using `%` directly all over the place - code can be bard to read and you can't readily search for transitions to/from the id-type (which is why having the `module MyType` might be better in general)
- you're using a Type Alias in some cases, which is rarely a good thing
- biggest 'hole' is that it's not addressable as a `Type` - i.e. if you want FsCheck to use a particular Arb for some kind of Id, you can't do that in a general way. Some hacks:

```fsharp
let (|Id|) (x : Guid) = x.ToString "N" |> FSharp.UMX.UMX.tag
let inline mkId () = Guid.NewGuid() |> (|Id|)
let (|Ids|) (xs : Guid[]) = xs |> Array.map (|Id|)
let (|ToList|) (xs : 'T[]) = Array.toList xs

let [<Property>] prop (Ids (ToList tickets), Ids items) = 
   ... (where tickets is a XyzId[] and items is an AbcId list)
```

The samples folder in Equinox has some some usages that you might want to peep around - I also have comments around this stuff (none of this is actually using STJ yet - that's a big TODO in https://github.com/jet/FsCodec/issues/14, hence my lurking here!) https://github.com/jet/equinox/blob/master/samples/Store/Domain/Infrastructure.fs#L40
