### ISSUE TITLE
How would I serialize read-only property of a record?

### ISSUE THREAD

**Issue by xperiandri** [Tarmil/FSharp.SystemTextJson#66]
I have a type like this
```
type Mesago =
    { Dialogo : DialogoID
      From : UzantoID
      Content : MesagoContent
      SentAt : DateTime }
    with
        [<JsonPropertyName("id")>]
        member mesago.ID =
            { SentAt = mesago.SentAt
              From = mesago.From }
        [<JsonIgnore>]
        member mesago.IDValue =
            mesago.ID |> MesagoID.value
```
How can I serialize ID property along with others?

**Comment by Tarmil** [comment]
Since version 1.0, the attribute `JsonInclude` can be put on the property that should be serialized. Alternately, the option `includeRecordProperties` will include all record properties (unless they have the `JsonIgnore` attribute). https://github.com/Tarmil/FSharp.SystemTextJson/blob/master/docs/Customizing.md#include-record-properties
